# Generated by Django 3.1 on 2021-09-10 14:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('service_area', '001_install_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Area')),
                ('service_area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_area', to='provider.serviceprovider')),
            ],
        ),
    ]
