version: '3.7'
services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  db:
    image: mdillon/postgis
    volumes:
      - mozio_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mozio_django
      - POSTGRES_PASSWORD=mozio_django
      - POSTGRES_DB=mozio_django_dev

volumes:
  mozio_data:
